{"version":3,"file":"bundle.js","mappings":";;;;;;AAAa;AACb;AACA,kBAAkB;AAClB;AACA;AACA;AACA;AACA;AACA;AACA;AACA,KAAK;AACL;AACA;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA;AACA,KAAK;AACL;AACA;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA;AACA,KAAK;AACL;AACA;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA;AACA,KAAK;AACL,kCAAkC;AAClC;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA;AACA,KAAK;AACL,kCAAkC;AAClC;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA;AACA,KAAK;AACL,gCAAgC;AAChC;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA,IAAI;AACJ;AACA;AACA;AACA;AACA;AACA,KAAK;AACL,EAAE;AACF,+BAA+B;AAC/B","sources":["webpack://3-mdul-loyiha-form-json-with-the-xampp-with-the-server-json/./src/script.js"],"sourcesContent":["\"use strict\";\r\n\r\n// console.log(a);// yani bu logda hech narsa yo'q lekin pastdagi logda hello world bor lekin run code qilinganda butun loyiha hato berepti(masalan bu fileda katta loyiha bo'lgan taqdirdaham hammasi buzulib ketgan bo`lardi hammasiga hato bervorgan bo'lardi chunki birinchi logdagi a yo'q narsa)\r\n\r\n// console.log(\"Hello world\");\r\n\r\n//try/catch yani hatolarni ushlab berish yani butun loyihada bitta hato bo'lsa shu bitta hato sabab butun loyiha buzulib tashlamasdan hatoni ushlab beradi\r\n\r\n// try {\r\n//     console.log(\"Work\");\r\n// } catch (error) {\r\n//     console.log(\"Error\");\r\n// }\r\n// console.log(\"Done\");//shu holatda run kode qilinganda work,done chiqepti error esa chiqmepti\r\n\r\n// try {\r\n//     console.log(\"Work\");\r\n//     console.log(a);\r\n//     console.log(\"Procecsing\");\r\n// } catch (error) {\r\n//     console.log(\"Error\");\r\n// }\r\n// console.log(\"Done\");//bu holatda run code qilinganda work,error,done chiqepti hullas catch functsiyasi va uning parametiridagi error tryni ichidagi logdagi hato a logini ushlab berib qolganini chiqardi yani bitta hato sabab butun loyiha hato bermadi aynan hato bo'lhan joyini kod o'qish tartibi bilanchiqarib berdi\r\n\r\n// try {\r\n//     console.log(\"Work\");\r\n//     console.log(a);\r\n//     console.log(\"Procecsing\");\r\n// } catch (error) {\r\n//     console.log(error);\r\n// }\r\n// console.log(\"Done\");//bu holatda birinchi  work,ikkinchi ReferenceError: a is not defined at script.js:27:1 at script.js:32:21,va uchinchi done chiqdi ///yani ReferenceError,da 27chi qatordagi (a) ni hato ekanligini va 30chi qatordagi errorni hatoligini consolda ko'rsatdi 30 chi qatordagi errorni hatoligini sababi shuki \"\"ahunaqa qavus ichiga olinmadi error hato sababi shu\r\n\r\n// try {\r\n//     console.log(\"Work\");\r\n//     console.log(a);\r\n//     console.log(\"Procecsing\");\r\n// } catch (error) {\r\n//     console.log(error.message);//bu error object qaytaradi yani object hissoblanadi name qo`shilganda hatoni nomini beradi yani reference error\r\n// }\r\n// console.log(\"Done\");//bu holatda birinchi  work,ikkinchi ReferenceError: a is not defined at script.js:27:1 at script.js:32:21,va uchinchi done chiqdi ///yani ReferenceError,da 27chi qatordagi (a) ni hato ekanligini va 30chi qatordagi errorni hatoligini consolda ko'rsatdi 30 chi qatordagi errorni hatoligini sababi shuki \"\"ahunaqa qavus ichiga olinmadi error hato sababi shu\r\n\r\n// try {\r\n//     console.log(\"Work\");\r\n//     console.log(a);\r\n//     console.log(\"Procecsing\");\r\n// } catch (error) {\r\n//     console.log(error.message);//bu error object qaytaradi yani object hissoblanadi message qo`shilganda a is not defined chiqadi yuani hatoni habarini beradi adresi va nomi bilan hullas catchda hatoni topib olsa bo'larkan\r\n// }\r\n// console.log(\"Done\");//bu holatda birinchi  work,ikkinchi ReferenceError: a is not defined at script.js:27:1 at script.js:32:21,va uchinchi done chiqdi ///yani ReferenceError,da 27chi qatordagi (a) ni hato ekanligini va 30chi qatordagi errorni hatoligini consolda ko'rsatdi 30 chi qatordagi errorni hatoligini sababi shuki \"\"ahunaqa qavus ichiga olinmadi error hato sababi shu\r\n\r\n// try {\r\n//     console.log(\"Work\");\r\n//     console.log(a);\r\n//     console.log(\"Procecsing\");\r\n// } catch (error) {\r\n//     console.log(error.stack);//bu error object qaytaradi yani object hissoblanadi stackda hatolarni ro'yhati qatorini raqami chiqadi ustiga bosilsa to`g`ri hatoga olib kiradi\r\n// }\r\n// console.log(\"Done\");//bu holatda birinchi  work,ikkinchi ReferenceError: a is not defined at script.js:27:1 at script.js:32:21,va uchinchi done chiqdi ///yani ReferenceError,da 27chi qatordagi (a) ni hato ekanligini va 30chi qatordagi errorni hatoligini consolda ko'rsatdi 30 chi qatordagi errorni hatoligini sababi shuki \"\"ahunaqa qavus ichiga olinmadi error hato sababi shu\r\n\r\n// const btn=document.querySelector(\".click\")\r\n// btn.addEventListener(\"click\", () =>{\r\n//     console.log(\"Click\");\r\n// })//bu holatda aboute.htmlda hato chiqepti chunki ungaham bundle.js ulangan addseventlistenner yo`q degan hato chiqarepti buning sababi webpack orqali bundle.js bilan ulangani uchun\r\n\r\nconst btn = document.querySelector(\".click\");\r\ntry {\r\n    btn.addEventListener(\"click\", () => {\r\n        console.log(\"Click\");\r\n    });\r\n} catch (error) {\r\n    console.log(error.message);//yoki name yozsaham hatoni nomini chiqaradi yani bu yerda index.htmldagi buttonga click qilinganda aboute.html da hatoni sababio chiqdi yani hatoni topib berdi bu sabab dasturchi hatoni topishi va bartaraf qilishi mumkun\r\n}\r\n"],"names":[],"sourceRoot":""}